name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # will be "bismarafique" in your repo secrets
        password: ${{ secrets.DOCKER_PASSWORD }}   # will be "abc123456" in your repo secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: bismarafique/registration-app:latest

    - name: Run container (optional)
      run: |
        docker run -d -p 3000:3000 --name reg-app -e MONGO_URI=${{ secrets.MONGO_URI }} bismarafique/registration-app:latest
